### PR TITLE
Document api

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
Top level page:

screenshot from 2016-09-19 19-09-31

cmake module page:

screenshot from 2016-09-19 19-09-44

cython page:

screenshot from 2016-09-19 19-09-58

numpy page:

screenshot from 2016-09-19 19-10-08

python extensions:

screenshot from 2016-09-19 19-10-19

**Comment by jcfr** [comment]
Cc: @thewtex @opadron

**Comment by jcfr** [comment]
Integrated in https://github.com/scikit-build/scikit-build/commit/459b04395637952fcaf4bb5604c57d67ba39facc

**Comment by thewtex** [comment]
Nice!

**Pull request closed without merging**
