### PR TITLE
CMake Improvements/skbuild features/demo applications

### PR DESCRIPTION
**Pull request by opadron**
So, when I started putting together example applications that were more involved than "hello, world", I soon realized that I needed more tooling improvements to support these new apps.  What started out as an effort to add example applications grew to include CMake scripts as well as several improvements to scikit-build.  I realize this changeset is on the large side, but everything here is related, so I figured breaking things up would obscure more than help.

There's a few technical choices I made while putting this together.  I made them just so that I could make progress, but we should take this time to discuss them in detail and make sure we are all happy with where things are going.  I expect this PR to remain a work in progress for a while as we take the time to work out all the details.

The CMake scripts are improvements that I'd like to see eventually contributed upstream.  This PR should serve as the temporary home until we get those pieces sufficiently polished and ready to propose to the CMake maintainers.

Other than that, I've assembled my notes below.  These notes include a summary of the changes, and a TODO list of things we'll probably want to take care of.

##### scikit-build improvements

 - "_skbuild" directories are now ignored by git.
 - added several changes in how the various staging directories are handled
   - all temporary staging directories are now contained in a top-level directory named "_skbuild"
     - changed the name of the top-level directory from "skbuild" to "_skbuild".
   - Within "_skbuild" are directories with new corresponding constants in `skbuild/cmaker.py`.
     - Location of the CMake project build directory (`cmaker.CMAKE_BUILD_DIR`) is now "_skbuild/cmake-build".
       - changed the name of the CMake project build directory from "cmake" to "cmake-build".
     - Location of the CMake project installation directory (`cmaker.CMAKE_INSTALL_DIR`) is now "_skbuild/cmake-install".
       - changed the constant in `cmaker.py` from `PACKAGE_BUILD_DIR` to `CMAKE_INSTALL_DIR`
       - changed the name of the CMake project installation directory from "lib" to "cmake-install"
     - Location of the package preparation directory used by distutils (`cmaker.DISTUTILS_INSTALL_DIR`) is now "_skbuild/distutils".
     - added custom subclasses of the `build`, `install`, and `clean` commands in order to get distutils to use the new directory.
       - works around a bug in distutils: https://bugs.python.org/issue1011113
         - patches provided, but no updates since 2014
 - skbuild now recognizes the `py_modules` argument and matches entries in the CMake install manifest to modules listed here.
 - skbuild now recognizes the `scripts` argument and matches entries in the CMake install manifest to scripts and executables listed here.
 - skbuild now recognizes the `data_files` argument and will now treat entries in the CMake install manifest that are not otherwise mentioned in the original `setup()` call as generic data files.
   - skbuild still doesn't properly handle items that are installed to paths that are not within the project root.  skbuild should probably not even attempt to deal with such entries, and instead refuse to proceed with an error message.
   - Currently, generic data files are installed in the target distribution's `site-packages` directory; alongside any other packages.  This is in contrast to distutil's behavior, which is to install data files directly under the prefix.  This change was made to support stand-alone extension modules that currently can only be installed as generic data files.  These files must be installed alongside other packages, but should not have to know the correct spelling of a distribution's `site-packages` directory (e.g.: `lib/python2.7/site-packages`, `$HOME/.local/lib/python3.5/...`)

##### CMake improvements

 - Added several CMake scripts for improved handling of Cython code, and improved handling of Python extension modules.  This effort is an amalgamation of existing code in CMake, CMake code by @thewtex and others (see [thewtex/cython-cmake-example/cmake/UseCython.cmake](https://github.com/thewtex/cython-cmake-example/blob/master/cmake/UseCython.cmake)), and improvements by @opadron.
   - added `tests/samples/cmake-files/FindCython.cmake`
   - added `tests/samples/cmake-files/FindPythonExtensions.cmake`
     - added new CMake function `python_extension_module`
     - added new CMake function `python_standalone_executable`
     - added new CMake function `python_modules_header`
     - see documentation for more details
   - added `tests/samples/cmake-files/UseCython.cmake`
     - added new CMake function `add_cython_target`
     - see documentation for more details

##### Test Applications

 - Added two example applications for demo and testing purposes.
   - pen2-cython: Double pendulum simulation implemented in Cython
     - project root: skbuild/tests/samples/pen2-cython
     - install and run `pen2_cython --help` for details
   - tower-of-babel: Technical stress-test that tests interoperability of pure-python and compiled extension modules of various linkages, calling conventions, and programming technologies.
     - project root: skbuild/tests/samples/tower-of-babel
     - install and run `tbabel --help` for details
     - NOTE: among the extension modules are dynamically-linked modules that, due to an interraction between how CMake uses RPaths and how scikit-build packages binaries, cannot normally be found without updating environment variables.  For Linux and OSX, `LD_LIBRARY_PATH` and `DYLD_LIBRARY_PATH` must be amended to include the current distribution's `site-packages` directory, respectively.  I do not yet know what changes are necessary on Windows.

##### TODO:
 - [ ] Extend testing coverage to include the new apps and new features.

 - [x] Refactor the custom distutils command subclasses so that they are accessible for other packages -- in case they want to work around us just as we did distutils.

 - [x] Restore the default handling of generic data files so that it matches up with distutils' default behavior.  To handle stand-alone extension modules, we'll need to add extra handling logic for the `py_modules` argument; we would list these modules under `py_modules`, and leave it to scikit-build to recognize them and place them accordingly.

 - [x] Add a final check to the manifest processing loop so that skbuild refuses to handle files installed outside of the project root.

 - [ ] There are multiple bugs in the way command line arguments are processed and forwarded in scikit-build.  It's not clear if they were introduced by these changes, or if they predate them.

   - [ ] There is a bug when trying to specify the desired CMake build type via the `--build-type` option in scikit-build.  It seems that some sections of the code are looking for `CMAKE_BUILD_DIR/CMAKE_BUILD_TYPE` as the ultimate location of the cmake build directory.  I think handling multiple builds in one tree is desirable and we should probably extend this handling to the other temporary staging directories, but right now, these improvements were not expecting this.  We'll need to go through the various code sections and make sure everyone's on the same page.

   - [ ] On a related note, I tried to pass options directly to CMake through scikit-build using the `--` argument seperator.  Scikit-build is currently written to expect up to three sections of such options: the first for scikit-build options, the second for CMake config options, and the third for options to the build step.  However, since CMake is used to drive the build step, options meant for the actual build tool (e.g.: make) must be separated by another `--` separator.  Currently scikit-build fails to properly handle this fourth separator.

 - [x] Add option to the `add_cython_target` function to override the variable name used to store the location to the generated source file.

 - [x] Remove TODO note in `add_cython_target` regarding C vs C++ output.  So far, no problems have been encountered one way or the other during development and testing.

 - [ ] Currently the only way to add to the Cython module search path for `add_cython_target` is to use the outdated `include_directories` CMake command.  Ideally, we would be able to use `target_include_directories` or something similar.  This may involve the creation of an actual CMake target.

 - [x] Remove the FindDebugger.cmake file (used just for debugging cmake targets).

 - [x] Update the `python_modules_header` function so that the `FORWARD_DECL_MODULES_VAR` option is renamed to `FORWARD_DECL_MODULES_LIST` and that the list in question is passed by value.

 - [x] Add option to the `python_modules_header` function to override the variable names used to store the locations of the generated header file as well as that of the directory containing it.

 - [x] Clean up tower-of-babel boost module header files.  Use `tbabel_boost_common.h` to minimize code duplication.

### CODE REVIEW

**Comment by opadron** [comment]
It looks like circleci keeps failing to install gfortran?

**Comment by opadron** [comment]
👍

**Comment by opadron** [comment]
Here are the remaining task items.  I'd like to move these over to a new testing PR, and call this one "ready".

 - [ ] Extend testing coverage to include the new apps and new features.

 - [ ] There are multiple bugs in the way command line arguments are processed and forwarded in scikit-build.  It's not clear if they were introduced by these changes, or if they predate them.

   - [ ] There is a bug when trying to specify the desired CMake build type via the `--build-type` option in scikit-build.  It seems that some sections of the code are looking for `CMAKE_BUILD_DIR/CMAKE_BUILD_TYPE` as the ultimate location of the cmake build directory.  I think handling multiple builds in one tree is desirable and we should probably extend this handling to the other temporary staging directories, but right now, these improvements were not expecting this.  We'll need to go through the various code sections and make sure everyone's on the same page.

   - [ ] On a related note, I tried to pass options directly to CMake through scikit-build using the `--` argument seperator.  Scikit-build is currently written to expect up to three sections of such options: the first for scikit-build options, the second for CMake config options, and the third for options to the build step.  However, since CMake is used to drive the build step, options meant for the actual build tool (e.g.: make) must be separated by another `--` separator.  Currently scikit-build fails to properly handle this fourth separator.

 - [ ] Currently the only way to add to the Cython module search path for `add_cython_target` is to use the outdated `include_directories` CMake command.  Ideally, we would be able to use `target_include_directories` or something similar.  This may involve the creation of an actual CMake target.

**Comment by jcfr** [comment]
@opadron  If not already the case, would it make sense to consolidate #36 and #38 together ?  Or integrating this Pr into master and rebasing the other topic ?

**Comment by opadron** [comment]
@jcfr I was planning on the latter.  In fact, I may end up just splitting things up into separate PRs, anyway; I'm not crazy about how large these changes have gotten.

**Comment by jcfr** [comment]
> smaller PRs; I'm not crazy about how large these changes have gotten

Roger that. Would be nice to see some of the nice bug fixes and features be integrated :+1:

**Comment by opadron** [comment]
superseded by #43

**Pull request closed without merging**
