### PR TITLE
setuptools_wrap: Remove cmake_process_manifest_hook keyword from argument dict

### PR DESCRIPTION
**Pull request by Jmennius**
So that setuptools won't complain about unknown setup options.

### CODE REVIEW

**Comment by Jmennius** [comment]
Need #494 for tests to pass (I'll rebase then).

**Comment by jcfr** [comment]
> Need #494 for tests to pass (I'll rebase then).

Thanks for your contribution  :pray: 

Few nitpicks:
* [ ] add entry to [CHANGES](https://github.com/scikit-build/scikit-build/blob/master/CHANGES.rst)
* [ ] update commit message. See below for a suggestion
* [ ] bonus: any test that could be improved to prevent future regression like this one ? 

```
setuptools_wrap: Fix unknown setup options related to cmake_process_manifest_hook keyword

This commit addresses a regression introduced in 66d7a32  (Add hook to process
cmake install manifest) and prevents setuptools from complaining about unknown
setup options.

It removes cmake_process_manifest_hook keyword from argument dict.
```

**Comment by Jmennius** [comment]
Thanks for the feedback!

I've implemented first two points but I'll take a look at tests later :)

**Comment by jcfr** [comment]
Will integrate after Continuous integration pipeline completes.

**Pull request merged**
