### PR TITLE
ci: Fix Fedora tests

### PR DESCRIPTION
**Pull request by LecrisUT**
- Switched to tmt downstream plans. Will probably have to switch back for `rpmlint` since we cannot upload the `rpmlintrc` file
- Enabled `fedora-all` targets

### CODE REVIEW

**Comment by LecrisUT** [comment]
I wanted to also enable the fortran tests, but they seem to be picking up genuine errors. Not sure how worth it is to address these though:
```
CMake Error at /builddir/build/BUILD/scikit-build-0.17.6/skbuild/resources/cmake/FindF2PY.cmake:85 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)
```
https://copr.fedorainfracloud.org/coprs/g/scikit-build/scikit-build/build/6759728/

**Comment by LecrisUT** [comment]
Ok, the only failing tests are some deprecation message from `setuptools` using `pkg_resources` I think:
```
>   warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
E   DeprecationWarning: pkg_resources is deprecated as an API
```
weird though, because this is supposed to be filtered:
```
  'ignore: pkg_resources is deprecated as an API:DeprecationWarning:setuptools',
```
Not sure why this is not being picked up

**Comment by henryiii** [comment]
```
python-scikit-build.spec:43: W: unversioned-explicit-provides bundled(cmake(FindCython))
python-scikit-build.spec:44: W: unversioned-explicit-provides bundled(cmake(FindPythonExtensions))
python-scikit-build.spec:45: W: unversioned-explicit-provides bundled(cmake(UseCython))
python-scikit-build.spec:46: W: unversioned-explicit-provides bundled(cmake(UseF2PY))
python-scikit-build.spec:47: W: unversioned-explicit-provides bundled(cmake(UsePythonExtensions))
python3-scikit-build.noarch: E: unused-rpmlintrc-filter "spelling-error.*\b(setuptools)\b"
python-scikit-build.spec: W: invalid-url Source0: scikit-build-0.17.6.tar.gz
 2 packages and 0 specfiles checked; 1 errors, 6 warnings, 1 badness; has taken 0.3 s 
```

**Comment by henryiii** [comment]
That space is weird. Maybe that's it?

**Comment by LecrisUT** [comment]
The error is within the spec file `%description`. I think it's just the regex failing there somehow. I'll look into it tomorrow. Should change it to use the downstream tests anyway

**Comment by LecrisUT** [comment]
> That space is weird. Maybe that's it?

Oh I forgot there were 2 issues and rebased  out your fix. Yeah, the issue was with the space

> The error is within the spec file `%description`. I think it's just the regex failing there somehow. I'll look into it tomorrow. Should change it to use the downstream tests anyway

It's quite annoying that the dictionary changed in between the fedora version, so only rawhide is reporting spelling error, but then F38 is complaining that the rpmlintrc file has unused checks. For now I just reworded the `%description`, but probably will have to fix the linter upstream to use specific versions

**Comment by henryiii** [comment]
Uhh, setup-tools looks bad, but guess we'll have to go with that for now. "setuptools" almost seems like it's common enough to include in a dictionary.

**Comment by LecrisUT** [comment]
I agree, this spell checker was reported and we are trying to convert it to a warning:
https://bugzilla.redhat.com/show_bug.cgi?id=2260329

**Pull request merged**
