### PR TITLE
Add hide listing option

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
@thewtex When you have a chance, I would appreciate your feedback on the `doc/usage` commit:

See https://github.com/scikit-build/scikit-build/pull/204/commits/f112a8bd252edbd7711c6c06aabd37ec09d9420b

Thanks

**Comment by thewtex** [comment]
@jcfr The new documentation is very nice! LGTM.

On a side note, we may want to consider using `pip install .`, `pip wheel .`, etc. in the documentation as it is the PyPA endorsed way forward for packaging in general.

**Comment by jcfr** [comment]
> On a side note, we may want to consider using pip install ., pip wheel ., etc. in the documentation as 
> it is the PyPA endorsed way forward for packaging in general.

Good point. I created issue #205 to track this.

**Comment by jcfr** [comment]
And thanks for the review :+1:

**Comment by jcfr** [comment]
After look at the first few Appveyor and Travis job, tests pass.

CircleCi has issue because the wrong build id is  associated with the PR ([692](https://circleci.com/gh/scikit-build/scikit-build/692) instead of [693](https://circleci.com/gh/scikit-build/scikit-build/693)

**Pull request merged**
