### PR TITLE
Use sdist command from setuptools instead of distutils

### PR DESCRIPTION
**Pull request by anibali**
Fixes https://github.com/scikit-build/scikit-build/issues/401.

Notes:
* Updated `generate_source_manifest.py` to produce a `MANIFEST.in` file instead of a `MANIFEST` file.

### CODE REVIEW

**Comment by anibali** [comment]
Work in progress

**Comment by jcfr** [comment]
Thanks for working on this :pray:

**Comment by jcfr** [comment]
Two errors on windows:

* test_hello_cython_sdist

```
___________________________ test_hello_cython_sdist ___________________________

iargs = (), ikwargs = {}

    @six.wraps(fun)
    def wrapped(*iargs, **ikwargs):
    
        if wrapped.tmp_dir is None:
            wrapped.tmp_dir = _tmpdir(fun.__name__)
            prepare_project(wrapped.project, wrapped.tmp_dir)
            initialize_git_repo_and_commit(
                wrapped.tmp_dir, verbose=wrapped.verbose_git)
    
>       with execute_setup_py(wrapped.tmp_dir, wrapped.setup_args, disable_languages_test=disable_languages_test):

tests\__init__.py:251: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\hostedtoolcache\windows\Python\3.7.2\x86\lib\contextlib.py:112: in __enter__
    return next(self.gen)
tests\__init__.py:233: in execute_setup_py
    six.exec_(setup_code)
setup.py:11: in <module>
    ???
skbuild\setuptools_wrap.py:456: in setup
    return upstream_setup(*args, **kw)
C:\hostedtoolcache\windows\Python\3.7.2\x86\lib\site-packages\setuptools\__init__.py:143: in setup
    return distutils.core.setup(**attrs)
C:\hostedtoolcache\windows\Python\3.7.2\x86\lib\distutils\core.py:148: in setup
    dist.run_commands()
C:\hostedtoolcache\windows\Python\3.7.2\x86\lib\distutils\dist.py:966: in run_commands
    self.run_command(cmd)
C:\hostedtoolcache\windows\Python\3.7.2\x86\lib\distutils\dist.py:985: in run_command
    cmd_obj.run()
skbuild\command\sdist.py:32: in run
    super(sdist, self).run(*args, **kwargs)
C:\hostedtoolcache\windows\Python\3.7.2\x86\lib\site-packages\setuptools\command\sdist.py:44: in run
    self.run_command('egg_info')
C:\hostedtoolcache\windows\Python\3.7.2\x86\lib\distutils\cmd.py:313: in run_command
    self.distribution.run_command(command)
C:\hostedtoolcache\windows\Python\3.7.2\x86\lib\distutils\dist.py:985: in run_command
    cmd_obj.run()
C:\hostedtoolcache\windows\Python\3.7.2\x86\lib\site-packages\setuptools\command\egg_info.py:296: in run
    self.find_sources()
C:\hostedtoolcache\windows\Python\3.7.2\x86\lib\site-packages\setuptools\command\egg_info.py:303: in find_sources
    mm.run()
C:\hostedtoolcache\windows\Python\3.7.2\x86\lib\site-packages\setuptools\command\egg_info.py:534: in run
    self.add_defaults()
C:\hostedtoolcache\windows\Python\3.7.2\x86\lib\site-packages\setuptools\command\egg_info.py:570: in add_defaults
    sdist.add_defaults(self)
C:\hostedtoolcache\windows\Python\3.7.2\x86\lib\distutils\command\sdist.py:226: in add_defaults
    self._add_defaults_python()
C:\hostedtoolcache\windows\Python\3.7.2\x86\lib\site-packages\setuptools\command\sdist.py:127: in _add_defaults_python
    build_py = self.get_finalized_command('build_py')
C:\hostedtoolcache\windows\Python\3.7.2\x86\lib\distutils\cmd.py:299: in get_finalized_command
    cmd_obj.ensure_finalized()
C:\hostedtoolcache\windows\Python\3.7.2\x86\lib\distutils\cmd.py:107: in ensure_finalized
    self.finalize_options()
skbuild\command\__init__.py:20: in finalize_options
    super(set_build_base_mixin, self).finalize_options(*args, **kwargs)
C:\hostedtoolcache\windows\Python\3.7.2\x86\lib\site-packages\setuptools\command\build_py.py:34: in finalize_options
    orig.build_py.finalize_options(self)
C:\hostedtoolcache\windows\Python\3.7.2\x86\lib\distutils\command\build_py.py:55: in finalize_options
    self.package_dir[name] = convert_path(path)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

pathname = 'hello/'

    def convert_path (pathname):
        """Return 'pathname' as a name that will work on the native filesystem,
        i.e. split it on '/' and put it back together again using the current
        directory separator.  Needed because filenames in the setup script are
        always supplied in Unix style, and have to be converted to the local
        convention before we can actually use them in the filesystem.  Raises
        ValueError on non-Unix-ish systems if 'pathname' either starts or
        ends with a slash.
        """
        if os.sep == '/':
            return pathname
        if not pathname:
            return pathname
        if pathname[0] == '/':
            raise ValueError("path '%s' cannot be absolute" % pathname)
        if pathname[-1] == '/':
>           raise ValueError("path '%s' cannot end with '/'" % pathname)
E           ValueError: path 'hello/' cannot end with '/'
```

* test_sdist_with_symlinks

```
__________________________ test_sdist_with_symlinks ___________________________

    def test_sdist_with_symlinks():
        project = 'issue-401-sdist-with-symlinks'
    
        tmp_dir = _tmpdir('test_sdist_with_symlinks')
        # NOTE: Existing prepare_project will remove symlinks, which renders the test useless
        prepare_project(project, tmp_dir)
    
        # Create a symbolic link
        # NOTE: We are creating the symlink after copying because prepare_project removes symlinks
        #       created in the samples directory.
        link_file = py.path.local(tmp_dir).join('VERSION')
        link_target = py.path.local(tmp_dir).join('VERSION.actual')
>       link_file.mksymlinkto(link_target, absolute=False)
E       AttributeError: 'LocalPath' object has no attribute 'mksymlinkto'
```

**Comment by anibali** [comment]
Thanks for helping out on this PR. Since POSIX symlinks aren't a thing on Windows, I just added a skip for that particular test.

**Comment by anibali** [comment]
It doesn't seem like any tests are failing anymore, but I'm not sure what's going on with this part of the CI pipeline:

```
==&gt;‌ Detecting CI provider‌
  -> Got branch from git/hg
  -> Got sha from git/hg
==&gt;‌ Preparing upload‌
    Error running `cd 'D:\a\1\s' && git ls-files`: None
XX&gt;‌ Skip processing gcov‌
==&gt;‌ Collecting reports‌
    Targeting specific files
    ‌+‌ .&#x2F;tests&#x2F;coverage.xml bytes=66423‌
==&gt;‌ Uploading‌
    .url https://codecov.io
    .query commit=ea5d13830b869d38bb2800dddc00ffb74104d2b3&branch=HEAD&token=<secret>&package=py2.0.15
    Pinging Codecov...
Error:‌ HTTP 400‌
Provided token is not a UUID.
```

**Comment by jcfr** [comment]
Thanks for fixing the remaining test.

The fix to specifically address the issue with symlink has been isolated and pushed into PR #408

After PR #408 is integrated, it will be good to rebase this one and move forward with integrating your changes to the implementation  of `generate_source_manifest`.

**Comment by jcfr** [comment]
>  but I'm not sure what's going on with this part of the CI pipeline:

We should fix that part : 

https://github.com/scikit-build/scikit-build/blob/893377695a14243ef5851873267b5b92bca88f4c/scikit-ci.yml#L62-L67

to be more robust. It looks like the env. variable `CODECOV_TOKEN` is set here :

https://github.com/scikit-build/scikit-build/blob/893377695a14243ef5851873267b5b92bca88f4c/azure-pipelines.yml#L65-L66

but to an incorrect value since the PR is from a fork and it has not access to the token.

**Comment by anibali** [comment]
Nice work with the separate PR, sorry that I couldn't figure that out myself. I'm not sure that the changes to `generate_source_manifest` are necessary anymore then.

**Comment by jcfr** [comment]
> Nice work with the separate PR, sorry that I couldn't figure that out myself.

Thanks. No need to be sorry, you really did the hard-work by providing an outstanding issue report,  implementing the test and following up with fixes :pray: 

> I'm not sure that the changes to generate_source_manifest are necessary anymore then.

I think  they are still relevant so that we can derive from sdist of setuptools. I think this is relevant to support https://github.com/pypa/setuptools_scm. From  what I could see `setuptools_scm` implements entry point `setuptools.file_finders` that are looked up by setuptools here:

https://github.com/pypa/setuptools/blob/83c667e0b2a98193851c07115d1af65011ed0fb6/setuptools/command/sdist.py#L17-L21

and declared by `setuptools_scm` here:

https://github.com/pypa/setuptools_scm/blob/7f6c9cfa52a47f4df81e753965bc37ca430e8e21/setup.py#L68-L69

**Comment by jcfr** [comment]
Notes:
* Need to revisit fix for failing `test_hello_cython_sdist` test proposed  in https://github.com/scikit-build/scikit-build/compare/9564778b832fe624b3fe3be33c57e700b36a68a6..21182579dcbad4343d7dd71b316470ecd537f514#diff-87a3bc14bb92fa1b5f6cd8bcb7aeaca8.

**Comment by anibali** [comment]
Ah, I didn't realise that the trailing slash was deliberate, I don't think I've seen anyone do it like that in the wild. My bad!

**Comment by dralley** [comment]
What are the chances that this will be merged?

**Comment by henryiii** [comment]
Okay, added a warning for the trailing slash - I don't think we should (in setuptools wrapper mode) accept something setuptools does not.

**Comment by henryiii** [comment]
> What are the chances that this will be merged?

High. ;)

**Pull request merged**
