### PR TITLE
replace guide for setup_requires with in-tree backend

### PR DESCRIPTION
**Pull request by maxbachmann**
setup_requires is deprecated in setuptools and it is possible to achieve the same using an `in-tree backend`.

### CODE REVIEW

**Comment by maxbachmann** [comment]
todo the usage of LegacyVersion needs to be replaced, since it was removed from packaging. I think something like `get_cmake_version_tuple` would be useful.

**Comment by maxbachmann** [comment]
I am unsure when `get_requires_for_build_sdist` is called. Is this called to collect requirements to convert from source to sdist, or to build from the sdist?

**Comment by henryiii** [comment]
Yes, that's right. `get_requires_for_build_sdist` is called when making SDists.

**Comment by henryiii** [comment]
And this is a really interesting idea for scikit-build-core too...

**Comment by maxbachmann** [comment]
In RapidFuzz I do the same for ninja/make. In addition I only install them when wheels are available, since the source build requires cmake to be available anyways. When installation fails due to compiler errors / missing cmake I provide a pure python fallback implementation: https://github.com/maxbachmann/RapidFuzz/blob/main/_custom_build/backend.py

**Comment by henryiii** [comment]
Thanks! This technically does't increase our API footprint (since the use of the these parts of the API were already there), so I think it's fine to merge, though I'm hoping scikit-build's own backend will do this soon.

**Comment by maxbachmann** [comment]
> I'm hoping scikit-build's own backend will do this soon.

An implementation inside scikit-build would likely always install cmake when it is not available yet. Note that this would break my usage of scikit-build. I do provide a pure Python fallback in case the compilation breaks. However this breaks when the build has a non pure Python dependency, which fails to install. Right now I hack this in the following way:
```python
if cmake_available:
    use system version
elif cmake_wheel_available:
    install wheel
else:
    use pure Python version
```
It would be great to add the cmake/ninja dependencies as a install extra `scikit-build[cmake]`.

**Comment by henryiii** [comment]
No, what I mean is that `build-backend = "scikit_build_core.build"` will do pretty much exactly the recommendation in this PR by default, but would be customizable via `[tool.scikit-build.cmake]` settings.

**Pull request merged**
