### PR TITLE
Improve detection of python library path

### PR DESCRIPTION
**Pull request by rkaminsk**
This patch considers the LIBDIR variable from both `distutils.sysconfig` and `sysconfig`. This is necessary to correctly detect the python library path when using pypy with recent setuputils versions.  (See #618.)

### CODE REVIEW

**Comment by henryiii** [comment]
Any idea about the one failure?

**Comment by rkaminsk** [comment]
> Any idea about the one failure?

No, clue. It does not make sense to me. I can spend some more time tomorrow, if you are interested in this PR.

**Comment by henryiii** [comment]
Thanks, I would hope it would enable #624.

**Comment by rkaminsk** [comment]
I'll debug it and come back to you.

**Comment by rkaminsk** [comment]
I found the problem. I overlooked one case. Now it is working as intended.

**Pull request merged**
