### PR TITLE
Add flake8

### PR DESCRIPTION
**Pull request by jcfr**
Remaining style error:
```
$ flake8
./tests/samples/pen2-cython/src/__init__.py:186: [E202] whitespace before ')'
        cTran0.RotateZ(180.0*(th0      )/pi)  # noqa: E202
                                      ^
./tests/samples/pen2-cython/src/__init__.py:187: [E201] whitespace after '('
        cTran1.RotateZ(180.0*(      th1)/pi)  # noqa: E201
                              ^
./tests/samples/tower-of-babel/tbabel_python.py:7: [F841] local variable 'nCy' is assigned to but never used
    nCy = len(cy_routines)
    ^
./skbuild/cmaker.py:72: [C901] 'CMaker.configure' is too complex (43)
    def configure(self, clargs=(), generator_id=None):
^
./skbuild/distutils_wrap.py:63: [E731] do not assign a lambda expression, use a def
    absappend = lambda x: op.join(op.dirname(op.abspath(sys.argv[0])), x)
    ^

```

### CODE REVIEW

**Comment by thewtex** [comment]
:+1:  keep it styyylin'

**Comment by jcfr** [comment]
Here is the issue on appveyor:

```
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\projects\scikit-build\tests\test_skbuild.py", line 46, in test_generator_selection
    assert(len(tuple(filter(bool, (py_27_32, py_33_34, py_35)))) == 1)
AssertionError
----------------------------------------------------------------------
Ran 11 tests in 36.406s
FAILED (failures=1)
Traceback (most recent call last):
  File ".\ci\appveyor\driver.py", line 207, in <module>
    d.drive_test()
  File ".\ci\appveyor\driver.py", line 187, in drive_test
    ["python", "-m", "nose", "-v", "-w", "tests"] + extra_test_args)
  File ".\ci\appveyor\driver.py", line 73, in check_call
    return subprocess.check_call(*args, **kwds)
  File "C:\Python35\lib\subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '-m', 'nose', '-v', '-w', 'tests', '--exclude', 'fortran_compiler', '--exclude', 'pen2', '--exclude', 'tbabel']' returned non-zero exit status 1
```

most likely caused by:

```
          py_33_34 = (
             version.major == 3 and (
-                version.minor >= 3 and
+                version.minor >= 3 or
                 version.minor <= 4
             )
         )
```

**Comment by thewtex** [comment]
version.minor == 3 or version.minor == 4?

**Comment by jcfr** [comment]
Failure was introduced by a misunderstanding of PyCharm suggestions (and a long day travelling ...), it turns out that expanding the tool-tip,  it was possible to automatically apply the [DeMorgans](https://en.wikipedia.org/wiki/De_Morgan%27s_laws) laws and obtain:

```
3 <= version.minor <= 4
```

See 3699e16

References:
* http://stackoverflow.com/questions/21320961/is-there-any-advantage-to-using-demorgan-law-in-python
* https://blog.jetbrains.com/idea/2014/09/the-inspection-connection-issue-2/

**Comment by jcfr** [comment]
Et voila. I will now:
* [ ] re-organize the last two WIP comments
* [ ] fix the remaining flake8 issues
* [ ] update the CI to run flake8 when a PR is pushed

**Comment by thewtex** [comment]
Very nice!

**Comment by jcfr** [comment]
Since latest changes to the PR updated the flake8 config and enabled flake8 on travis (which is green), I am integrating.

**Pull request merged**
