### PR TITLE
[rebased] scikit-build improvements/New CMake modules/New sample projects/CI testing

### PR DESCRIPTION
**Pull request by opadron**
concludes #36 and #38

### CODE REVIEW

**Comment by opadron** [comment]
I don't know what happened to Travis, but I only see circle, and appveyor.

:-1:

**Comment by opadron** [comment]
I found this: http://help.appveyor.com/discussions/problems/3900-error-uploading-artifact-to-google-storage

**Comment by jcfr** [comment]
Good find.

**Comment by jcfr** [comment]
@opadron May be work adding an other function to the driver to invoke code mentioned in http://help.appveyor.com/discussions/problems/3900-error-uploading-artifact-to-google-storage

Something like
```
self.check_call(
    [
        'powershell.exe', 
        '-Command',
        'Get-EventLog AppVeyor -newest 10 | Format-List'
    ]
)
```

**Comment by opadron** [comment]
Unfortunately, there are some things that can't be moved into the driver script, this likely being one of them, so I just added the lines to `appveyor.yml`, directly.

**Comment by opadron** [comment]
Welp, looks like Travis decided to come to work, today. 😄

**Comment by opadron** [comment]
@scikit-build/developers We're all green and ready to go, here.  I'm looking forward to finally getting this merged.

**Comment by jcfr** [comment]
@opadron Thanks for the note. This is great. I will do a final round of testing locally and merge it.

**Comment by jcfr** [comment]
Since I don't have a fortran compiler installed, test pass running them using:
```
PATH=/home/jcfr/Software/cmake-3.5.2-Linux-x86_64/bin:$PATH nosetests -v -w tests --exclude pen2 --exclude tbabel --exclude fortran_compiler
```

I will report back after installing a fortran compiler

**Comment by jcfr** [comment]
Since all tests pass (except `pen2` and `tbabel` that will be addressed later), I am merging.

```
PATH=/home/jcfr/Software/cmake-3.5.2-Linux-x86_64/bin:$PATH \
  nosetests -v -w tests --exclude pen2 --exclude tbabel
[...]
----------------------------------------------------------------------
Ran 11 tests in 4.382s
OK
```

**Comment by opadron** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Pull request merged**
