### PR TITLE
skbuild: Prompt user with direction to install compiler if not installed

### PR DESCRIPTION
**Pull request by jcfr**
See #27

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @thewtex

**Comment by jcfr** [comment]
xref #225

**Comment by jcfr** [comment]
Integrated in https://github.com/scikit-build/scikit-build/commit/d592c8084a7e0502d9da9e7aacf0e465be40cc67

**Comment by thewtex** [comment]
Awesome!

**Pull request closed without merging**
