### PR TITLE
Add support for PyPy and setup continuous integration

### PR DESCRIPTION
**Pull request by mattip**
Let's see if this works.

Since PyPy is still in a catch-up mode where it releases every 3-6 months, I preferred to `wget` the latest release.

Follow on from #407, will fail until that is merged

### CODE REVIEW

**Comment by mattip** [comment]
It seems there is a problem installing cmake in the pre-install step, since it depends on skbuild (recursive dependency?):
```
[scikit-ci] Executing: pip install cmake
Collecting cmake
  Downloading https://files.pythonhosted.org/packages/72/7b/8d3d83f884283ddfc86ca407d10152d66b84dff5baf5ed4537c127f988cb/cmake-3.13.3.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zcccb0ai/cmake/setup.py", line 7, in <module>
        from skbuild import setup
    ModuleNotFoundError: No module named 'skbuild'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-zcccb0ai/cmake/
```

**Comment by jcfr** [comment]
>  problem installing cmake

Indeed, cmake wheel are currently specific to the python abi. I think this will be addressed implementing the approach documented in https://github.com/scikit-build/scikit-build/issues/420 . 

Do you think that wheel with tag like `py2.py3-none-manylinux2010_x86-64` will be installable on pypy ?

**Comment by mattip** [comment]
> Do you think that wheel with tag like py2.py3-none-manylinux2010_x86-64 will be installable on pypy

Yes, once I updated pip to version 19, this command `pypy3.6-v7.1.1/bin/pypy3 -mpip install imageio-ffmpeg` downloaded and installed `imageio_ffmpeg-0.3.0-py3-none-manylinux2010_x86_64.whl`

**Comment by mattip** [comment]
Rebased off master to get the new cmake package.

The build failed. While watching it, it seemed to cycle infinitely through some pep-8 flake thing, checking all the site packages. Eventually I think it timed out.

When I try to reproduce the steps localy, I cannot run`python -mci install`. When I "lie" to it, by running `APPVEYOR=True python -m ci install`, the process escapes the virtual environment and `pip install cmake` tries to install it to my OS python2.

**Comment by jcfr** [comment]
> it seemed to cycle infinitely through some pep-8 flake thing

The issue was that folders for pypy and associated environment were created in the scikit-build source directory and flake8 was trying to lint all the associated files. This is now fixed by creating directories in the parent folder.

>  When I "lie" to it, by running APPVEYOR=True python -m ci install

To "simulate" Azure Pipelines locally, the variables `TF_BUILD=true` and 'AGENT_OS=Linux' could be set.

**Comment by jcfr** [comment]
It turns out that `get_python_include_dir` does not need to be modified. Indeed the header `Python.h` is also available within PyPy installation.

Regarding `get_python_library`, I fixed and simplified the list adding `pypy3-c`.

**Comment by mattip** [comment]
cool, tests pass

**Pull request merged**
