### PR TITLE
fix: conda cross-compile issue fix

### LINKED ISSUE #643: '_collections._tuplegetter' object has no attribute 'split'
On cross-compiling on macOS I'm getting:
```
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from skbuild import setup
  File "/Users/runner/miniforge3/conda-bld/frictionqpotfem-split_1643375000677/_build_env/venv/lib/python3.8/site-packages/skbuild/__init__.py", line 9, in <module>
    from .setuptools_wrap import setup  # noqa: F401
  File "/Users/runner/miniforge3/conda-bld/frictionqpotfem-split_1643375000677/_build_env/venv/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 39, in <module>
    from . import cmaker
  File "/Users/runner/miniforge3/conda-bld/frictionqpotfem-split_1643375000677/_build_env/venv/lib/python3.8/site-packages/skbuild/cmaker.py", line 20, in <module>
    from .constants import (CMAKE_BUILD_DIR,
  File "/Users/runner/miniforge3/conda-bld/frictionqpotfem-split_1643375000677/_build_env/venv/lib/python3.8/site-packages/skbuild/constants.py", line 62, in <module>
    _SKBUILD_PLAT_NAME = _default_skbuild_plat_name()
  File "/Users/runner/miniforge3/conda-bld/frictionqpotfem-split_1643375000677/_build_env/venv/lib/python3.8/site-packages/skbuild/constants.py", line 56, in _default_skbuild_plat_name
    if set(machine.split(";")) == macos_universal2_architectures:
AttributeError: '_collections._tuplegetter' object has no attribute 'split'
```
Reference: https://github.com/conda-forge/frictionqpotfem-feedstock/pull/57

I'm using:
```
scikit-build:          0.12.0-py38h6f2b01f_2         conda-forge
```

### PR DESCRIPTION
**Pull request by henryiii**
Closes #643.

### CODE REVIEW

**Comment by henryiii** [comment]
Ahh, we are in the windows-2016 brownout. :/ Should come back online in ~4 hours.

**Comment by tdegeus** [comment]
I can confirm that the first commit resolves my issues. I can try the second if you want https://github.com/conda-forge/frictionqpotfem-feedstock/pull/59

**Comment by henryiii** [comment]
Could you see if the `platform.machine()` version works (once it passes tests except for azure here)? That one is portable. Not sure why `mac_ver` is being used on windows, but, okay.

**Comment by henryiii** [comment]
If this works, I think we should cut a 0.13 release with this. We can collect a few more of the almost-done ones that just need a review for 0.14, then drop old MSVC & Python.

**Comment by tdegeus** [comment]
Great! Thanks! Could you ping me if released, then I can let through my package on conda-forge?

**Comment by henryiii** [comment]
I'll try to get to it today, depending on how much random other stuff breaks between now and then (packages like pip and zipp dropping Python 3.6 is constantly breaking conda-forge)

**Comment by henryiii** [comment]
Release is out (PyPI now, hopefully on conda-forge soon). Feel free to subscribe to releases on the repo, the would also ping you for new releases. ;)

**Comment by henryiii** [comment]
Should be out on conda-forge now too.

**Comment by tdegeus** [comment]
Thanks a lot @henryiii !! Working as a charm : https://github.com/conda-forge/frictionqpotfem-feedstock/pull/57

**Pull request merged**
