### PR TITLE
Revert "fix: MANIFEST.in data install location"

### PR DESCRIPTION
**Pull request by henryiii**
Reverts scikit-build/scikit-build#682

This might be causing problems, testing reverting it to see if it is.

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
This may be explaining a problem we ran into?

Our `MANIFEST.in` contains `LICENSE`

With scikit_build-0.13.1, [build logs](https://github.com/scipp/scipp/runs/5735222488?check_suite_focus=true) are:
```
...
copying LICENSE -> _skbuild/linux-x86_64-3.8/cmake-install/LICENSE
...
copying _skbuild/linux-x86_64-3.8/cmake-install/LICENSE -> _skbuild/linux-x86_64-3.8/setuptools/bdist.linux-x86_64/wheel/scipp-0.13.0.data/data/
```
With scikit_build-0.14.0, [build logs](https://github.com/scipp/scipp/runs/5849737928?check_suite_focus=true) are:
```
...
copying LICENSE -> _skbuild/linux-x86_64-3.8/cmake-install/src/scipp/LICENSE
...
error: can't copy '_skbuild/linux-x86_64-3.8/cmake-install/LICENSE': doesn't exist or not a regular file
...
```

Our call to `setup` uses `cmake_install_dir='src/scipp'`.

**Comment by GenieTim** [comment]
I am encountering similar problems as @SimonHeybrock with Manifest.im entries such as `include README.md` or `include CMakeLists.txt` (when `package_dir={"": "src"}`).

**Comment by kratsg** [comment]
> This may be explaining a problem we ran into?

Yeah, this is a bit confusing. Without it, you end up having data files outside of the packaged directory when installed (which is a bit awkward). You could get around this by specifying `src/scipp/LICENSE` in your `MANIFEST.in` but it doesn't seem to package it correctly. Not sure what is going on just yet.

**Comment by SimonHeybrock** [comment]
> You could get around this by specifying src/scipp/LICENSE in your MANIFEST.in but it doesn't seem to package it correctly.

I suppose it cannot, since `LICENSE` is in the top level folder, not in the `src/scipp` folder?

**Comment by GenieTim** [comment]
> > You could get around this by specifying src/scipp/LICENSE in your MANIFEST.in but it doesn't seem to package it correctly.

Another workaround seems to be to set `cmake_install_dir = ""`. Not sure about the implications here.

**Comment by kratsg** [comment]
@SimonHeybrock if you look at the install log, it seems that `scikit-build` will copy the files in MANIFEST.in over to that location in `cmake-install` so `pip` can find it there. My changes in the linked PR basically moved where the files got installed. The reason is that before those changes, you got this sort of unintended behavior of having files installed outside of the `site-packages` (notice where `LICENSE` etcetera are located)

```bash
$ python -m pip uninstall pylibmagic
Found existing installation: pylibmagic 0.2.1.dev0+g70ecf65.d20220407
Uninstalling pylibmagic-0.2.1.dev0+g70ecf65.d20220407:
  Would remove:
    /Users/kratsg/.pyenv/versions/3.8.6/LICENSE
    /Users/kratsg/.pyenv/versions/3.8.6/README.rst
    /Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pylibmagic-0.2.1.dev0+g70ecf65.d20220407.dist-info/*
    /Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pylibmagic/*
    /Users/kratsg/.pyenv/versions/3.8.6/pyproject.toml
    /Users/kratsg/.pyenv/versions/3.8.6/setup.cfg
    /Users/kratsg/.pyenv/versions/3.8.6/setup.py
    /Users/kratsg/.pyenv/versions/3.8.6/src/pylibmagic.egg-info/PKG-INFO
    /Users/kratsg/.pyenv/versions/3.8.6/src/pylibmagic.egg-info/SOURCES.txt
    /Users/kratsg/.pyenv/versions/3.8.6/src/pylibmagic.egg-info/dependency_links.txt
    /Users/kratsg/.pyenv/versions/3.8.6/src/pylibmagic.egg-info/requires.txt
    /Users/kratsg/.pyenv/versions/3.8.6/src/pylibmagic.egg-info/top_level.txt
    /Users/kratsg/.pyenv/versions/3.8.6/tests/test_compiled.py
    /Users/kratsg/.pyenv/versions/3.8.6/tests/test_import.py
    /Users/kratsg/.pyenv/versions/3.8.6/tests/test_package.py
Proceed (y/n)? y
```

**Comment by SimonHeybrock** [comment]
@kratsg Are you suggesting that we should move (or cmake install) our license (or readme) into that folder to avoid this problem? That is, *everything* should go into `package_dir`?

**Comment by kratsg** [comment]
> @kratsg Are you suggesting that we should move (or cmake install) our license (or readme) into that folder to avoid this problem? That is, _everything_ should go into `package_dir`?

Not necessarily. My point here is that the copying has already been done for you, just where these files get copied to for `pip` to pick up is what forces `pip` to install in different locations with respect to your package directory (but only for `scikit-build` projects). If you run a `pip install` in verbose mode using scikit-build @ 0.13.1, you see this (notice the lines towards the end copying my `MANIFEST.in` files over to `cmake-install/`) which is the default behavior. These are the files that are being picked up by python-packaging.

```
  Configuring Project
    Working directory:
      /Users/kratsg/pylibmagic/_skbuild/macosx-10.14-x86_64-3.8/cmake-build
    Command:
      cmake /Users/kratsg/pylibmagic -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/Users/kratsg/pylibmagic/_skbuild/macosx-10.14-x86_64-3.8/cmake-install/src/pylibmagic -DPYTHON_EXECUTABLE:FILEPATH=/Users/kratsg/.pyenv/versions/pylibmagic/bin/python -DPYTHON_VERSION_STRING:STRING=3.8.6 -DPYTHON_INCLUDE_DIR:PATH=/Users/kratsg/.pyenv/versions/3.8.6/include/python3.8 -DPYTHON_LIBRARY:FILEPATH=/Users/kratsg/.pyenv/versions/3.8.6/lib/libpython3.8.a -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/private/var/folders/cz/ysr8lt_90z37zyb25ds1sjcr0000gn/T/pip-build-env-amc5w2uq/overlay/lib/python3.8/site-packages/skbuild/resources/cmake -DCMAKE_MAKE_PROGRAM:FILEPATH=/private/var/folders/cz/ysr8lt_90z37zyb25ds1sjcr0000gn/T/pip-build-env-amc5w2uq/overlay/lib/python3.8/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.14 -DCMAKE_OSX_ARCHITECTURES:STRING=x86_64


  copying src/pylibmagic/_version.py -> _skbuild/macosx-10.14-x86_64-3.8/cmake-install/src/pylibmagic/_version.py
  copying src/pylibmagic/__init__.py -> _skbuild/macosx-10.14-x86_64-3.8/cmake-install/src/pylibmagic/__init__.py
  copying src/pylibmagic/_version.pyi -> _skbuild/macosx-10.14-x86_64-3.8/cmake-install/src/pylibmagic/_version.pyi
  copying src/pylibmagic/_version.py -> _skbuild/macosx-10.14-x86_64-3.8/cmake-install/src/pylibmagic/_version.py
  copying src/pylibmagic/__init__.py -> _skbuild/macosx-10.14-x86_64-3.8/cmake-install/src/pylibmagic/__init__.py
  copying src/pylibmagic/py.typed -> _skbuild/macosx-10.14-x86_64-3.8/cmake-install/src/pylibmagic/py.typed
  copying src/pylibmagic.egg-info/PKG-INFO -> _skbuild/macosx-10.14-x86_64-3.8/cmake-install/src/pylibmagic.egg-info/PKG-INFO
  copying src/pylibmagic.egg-info/SOURCES.txt -> _skbuild/macosx-10.14-x86_64-3.8/cmake-install/src/pylibmagic.egg-info/SOURCES.txt
  copying src/pylibmagic.egg-info/requires.txt -> _skbuild/macosx-10.14-x86_64-3.8/cmake-install/src/pylibmagic.egg-info/requires.txt
  copying src/pylibmagic.egg-info/top_level.txt -> _skbuild/macosx-10.14-x86_64-3.8/cmake-install/src/pylibmagic.egg-info/top_level.txt
  copying src/pylibmagic.egg-info/dependency_links.txt -> _skbuild/macosx-10.14-x86_64-3.8/cmake-install/src/pylibmagic.egg-info/dependency_links.txt
  copying tests/test_package.py -> _skbuild/macosx-10.14-x86_64-3.8/cmake-install/tests/test_package.py
  copying tests/test_compiled.py -> _skbuild/macosx-10.14-x86_64-3.8/cmake-install/tests/test_compiled.py
  copying tests/test_import.py -> _skbuild/macosx-10.14-x86_64-3.8/cmake-install/tests/test_import.py
  copying LICENSE -> _skbuild/macosx-10.14-x86_64-3.8/cmake-install/LICENSE
  copying README.rst -> _skbuild/macosx-10.14-x86_64-3.8/cmake-install/README.rst
  copying pyproject.toml -> _skbuild/macosx-10.14-x86_64-3.8/cmake-install/pyproject.toml
  copying setup.py -> _skbuild/macosx-10.14-x86_64-3.8/cmake-install/setup.py
  copying setup.cfg -> _skbuild/macosx-10.14-x86_64-3.8/cmake-install/setup.cfg
```

**Comment by kratsg** [comment]
But honestly, even worse than all of this is that the test I wrote for this seems to have the right expected behavior, but it seems to be different than what's happening now with `pip` and also seems to be different when using `python -m build` so I'm not completely sure how to reconcile the behavior of python packaging.

**Comment by kratsg** [comment]
More debugging, setting `cmake_install_dir="myinstall"` (and keeping `package_dir={"": "src"}`) gives me this structure

```
$ tree -d _skbuild/macosx-10.14-x86_64-3.8/cmake-install
_skbuild/macosx-10.14-x86_64-3.8/cmake-install
├── myinstall
│   ├── pkgconfig
│   ├── src
│   │   ├── pylibmagic
│   │   └── pylibmagic.egg-info
│   └── tests
└── src
    └── pylibmagic

8 directories
```

Under `_skbuild/macosx-10.14-x86_64-3.8/cmake-install/myinstall` - I have everything, including the MANIFEST.in files specified, in the right structure expected. However, under `_skbuild/macosx-10.14-x86_64-3.8/cmake-install/src/pylibmagic` seems to include only `__init__.py` and `_version.py`, but I'm not sure what's making that happen here.

**Comment by henryiii** [comment]
What about adding #582? It could be this just exposes the need for that fix without editable installs? The problem is you end up with files in two places (inside the install folder, and in the outer folder but specified with setuptools) that both need to go into the final wheel folder. I think we are removing the former currently, then previously mangling the later. So it's two bugs, and both need to be fixed together, possibly.

**Comment by henryiii** [comment]
Using a snippet provided by @kratsg, `docker run -it --rm python:3 bash -c 'pip install git+https://github.com/kratsg/pylibmagic@feat/usepackagedata'`, I was able to show that adding the fix in #582 does not fix this issue, so going to revert for now. Hopefully we can improve this in the future.

**Pull request merged**
