### PR TITLE
Adding start of a basic pure cpython module build with CMake.

### PR DESCRIPTION
**Pull request by blowekamp**
I have added a directory with a basic CPython module which can be build with CMake. There is still work to do to get it working with PyCMake.setup. Additionally, it's not currently being tested. It should provide a simple example to experiment with how things should be done.

### CODE REVIEW

**Comment by opadron** [comment]
Hi, all.  So, it looks like I've been assigned to see this PR through to resolution, so I'm necro-ing this thread.

As far as basic CPython modules go, we have [jcfr/python-cmake-custom-extension](https://github.com/jcfr/python-cmake-custom-extension), which has the latest changes necessary to work with #30.

So, is there any further action that is necessary for this PR?

**Comment by blowekamp** [comment]
Please take anything needed from here to help develop a comprehensive frame work for testing packaging and building with scikit build.

**Comment by opadron** [comment]
We'll be adding example apps to the testing soon, so, let's keep this open in case we need to borrow anything here.

And then once we have a few apps in place and tested, we can close this up.

How does that sound?

**Comment by jcfr** [comment]
> How does that sound?

Makes sense.

I also like the idea of having simple examples, adding directories like  `tests/samples/intocpython` could make sense.

**Comment by opadron** [comment]
We are almost done working on a large change set in #43 that should add several test projects.  In particular, please have a look at [hello](https://github.com/scikit-build/scikit-build/pull/43/commits/abc9221db54243ffbba344e08ee6bcf407fbb175) and [hello-cython](https://github.com/scikit-build/scikit-build/pull/43/commits/6d99ec0268f688f6c059dc6db6cbb55c3c9ecfa7).

I suggest this issue be resolved and closed once #43 is merged.

What do you think, @blowekamp?

**Comment by opadron** [comment]
I'm going to go ahead and close this.  Feel free to reopen if necessary.

**Pull request closed without merging**
