### PR TITLE
[WIP] Remove sample projects/Refactor CI driver

### PR DESCRIPTION
**Pull request by opadron**
Removes sample projects: "pen2-cython" and "tower-of-babel", in preparation for their move to their own projects repository.

Also, refactors more of the CI testing logic into driver scripts, in preparation for moving *it* to its own repository.

This PR is *super* WIP.  I expect the changes to break all the testing at first.

This PR should resolve or partially address #46, #63, #78 
This work should likely be merged with #97

### CODE REVIEW

**Comment by opadron** [comment]
Looks like good progress.  I'll keep working on tomorrow.

**Comment by jcfr** [comment]
See #104, it simplified testing and address the coverage issue

**Comment by opadron** [comment]
RDP'ing into an appveyor worker reveals that flake8 is just constantly crashing and hanging the build.  I can't tell what's going wrong; even running the script directly (`C:\Python27\Scripts\flake8.exe -v`) fails in the same manner.

Considering that we shouldn't have to run style tests on all platforms, I'm going to try removing style testing on appveyor.

**Comment by msmolens** [comment]
@opadron flake8 hanged on my local Windows machine as well after an error:

    pickle.PicklingError: Can't pickle '_subprocess_handle' object: <_subprocess_handle object at 0x0000000002F364F8>

Updating to the latest version looks like it fixes the problem, which is likely the one discussed here:
https://gitlab.com/pycqa/flake8/issues/164
and fixed here:
https://gitlab.com/pycqa/flake8/merge_requests/98

See requirements update PR: https://github.com/scikit-build/scikit-build/pull/121.

**Comment by opadron** [comment]
Neat, let's get that merged, and I'll try flake8 on windows, again.

**Comment by opadron** [comment]
https://ci.appveyor.com/project/scikit-build/scikit-build/build/0.0.1.66/job/rdt70r2hyoi8ne2a#L368

This is just more of what I was talking about in #121.  Building with MinGW, which worked perfectly fine before, suddenly doesn't.  No details about what happened when trying to compile, no error message, nothing.

AppVeyor really does deserve more of my ire than Travis, but the broader issue remains.  When CI comes back red, I can't afford to waste time eliminating the possibility that it has nothing to do with our tests.

**Comment by jcfr** [comment]
To follow up one our discussion with @opadron: Mingw should be skipped. It is already the case.

**Comment by jcfr** [comment]
Consider also:
* rebasing against master
* squashing commits

Thanks :+1:

**Pull request closed without merging**
