### PR TITLE
tests: add markers for isolated & nosetuptoolsscm

### PR DESCRIPTION
**Pull request by henryiii**
- tests: add marker for nosetuptoolsscm
- tests: add isolated marker

See #791.

### CODE REVIEW

**Comment by hroncok** [comment]
What if the nosetuptoolsscm tests were skipped when setuptools_scm is installed?

**Comment by hroncok** [comment]
If I understand the docs correctly https://docs.pytest.org/en/7.1.x/example/markers.html

If we add something like this to conftest.py:

```py
try:
    import setuptools_scm
except ImportError:
    HAS_SETUPTOOLS_SCM = False
else:
    HAS_SETUPTOOLS_SCM = True
    del setuptools_scm
    del sys.modules["setuptools_scm"]

def pytest_runtest_setup(item):
    for marker in item.iter_markers(name="nosetuptoolsscm"):
        if HAS_SETUPTOOLS_SCM:
            pytest.skip("This test does not work when setuptools_scm is installed")
```

**Comment by henryiii** [comment]
That's about how you'd do it (it's basically an inverted importorskip!), but to me, it seems that verifying that setuptools_scm is not present is normally helpful - you don't want a downstream package using scikit-build to be forced to use setuptools_scm, which unconditionally changes their build. This has helped at least one packager ensure that their build requirements were not leaked as install requirements, IIRC.

Of course, it should probably be a better failure than just some seemingly random tests failing.

**Comment by henryiii** [comment]
Okay, I've improved the error message when the tests aren't skipped. It still runs till it hits one, but then it errors out immediately with a better error.

**Comment by mgorny** [comment]
As a downstream packager, I'm completely confused by this. Does that mean that we're supposed to unmerge `setuptools_scm` before running the test suite (which — besides being very inconvenient for Gentoo users — is simply impossible because it's required by `hatch-vcs`)? Or are we supposed to skip these tests?

Also, `pytest.exit()` is horrible UX. It looks like the test suite suddenly terminated in the middle of test suite for no apparent reason, and the error is barely noticeable. I mean, if you don't look at exit status, at a first glance it looks as if the test suite succeeded.

**Pull request merged**
