### PR TITLE
ci/travis: Enable testing on osx. Fixes #97

### LINKED ISSUE #97: Enable testing on MacOSX

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
On MacOSX: Python need to be installed. Few options:
* [official binaries](https://www.python.org/downloads/)
* homebrew
* macports

**Comment by jcfr** [comment]
@msmolens When you have a chance, could you rebase the topic and have a look at this. I couldn't get the right version of CMake to be used.

Since @opadron is working on refactoring the ci infrastructure, sync with him.

**Comment by jcfr** [comment]
The report error is now this one:

```
$ export PATH=/usr/local/bin:$PATH; python setup.py test --args="$EXTRA_TEST_ARGS"

running test

Searching for setuptools==22.0.5

Best match: setuptools 22.0.5



Using /Users/travis/Library/Python/2.7/lib/python/site-packages

running egg_info

creating scikit_build.egg-info

writing requirements to scikit_build.egg-info/requires.txt

writing scikit_build.egg-info/PKG-INFO

writing top-level names to scikit_build.egg-info/top_level.txt

writing dependency_links to scikit_build.egg-info/dependency_links.txt

writing manifest file 'scikit_build.egg-info/SOURCES.txt'

reading manifest file 'scikit_build.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

warning: no previously-included files matching '__pycache__' found under directory '*'

warning: no previously-included files matching '*.py[co]' found under directory '*'

writing manifest file 'scikit_build.egg-info/SOURCES.txt'

running build_ext

Traceback (most recent call last):

  File "setup.py", line 85, in <module>

    cmdclass=commands

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup

    dist.run_commands()

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/Library/Python/2.7/site-packages/setuptools-4.0.1-py2.7.egg/setuptools/command/test.py", line 145, in run

  File "/Library/Python/2.7/site-packages/setuptools-4.0.1-py2.7.egg/setuptools/command/test.py", line 125, in with_project_on_sys_path

  File "/Library/Python/2.7/site-packages/setuptools-4.0.1-py2.7.egg/pkg_resources.py", line 742, in require

    Any distributions found are added to the environment.

  File "/Library/Python/2.7/site-packages/setuptools-4.0.1-py2.7.egg/pkg_resources.py", line 643, in resolve

    distributions.update(dict.fromkeys(resolvees))

pkg_resources.VersionConflict: (setuptools 4.0.1 (/Library/Python/2.7/site-packages/setuptools-4.0.1-py2.7.egg), Requirement.parse('setuptools==22.0.5'))
```

**Comment by jcfr** [comment]
Possibly related is https://github.com/travis-ci/travis-ci/issues/4194

**Comment by jcfr** [comment]
:+1: Very nice

Is it ready to be integrated ?

**Comment by msmolens** [comment]
:+1: Based on Travis running and passing the tests, this is suitable to be integrated. But note that some reimplementation is in order for this functionality to be integrated into the refactored CI framework in WIP #100. I can look at doing that if that part of the branch is somewhat stable.

**Comment by jcfr** [comment]
> some reimplementation [...]  integrated into the refactored CI framework in WIP #100.

Makes sense. Please work with @opadron to finalize this.

In the process, consider how work related to CI could be re-organized to better address issue #46

**Pull request merged**
