### PR TITLE
Fix Manifest bugs

### PR DESCRIPTION
**Pull request by henryiii**
This fixes #260 (using a cherry-picked commit on to current master to get correct attribution), and also fixes the auto MANIFEST generation if a project uses submodules (and if the git version is high enough). It also adds a regression test to ensure that `MANIFEST.in` is working. (Fails if `MANIFEST.in` is deleted)

### CODE REVIEW

**Comment by henryiii** [comment]
Any suggestions? it passes tests, the only x is due to codecov thinking that there are 0.07% fewer tested lines.

**Comment by henryiii** [comment]
@jcfr?

**Comment by jcfr** [comment]
Hi Henry,

I am travelling to the west coast for some vacation and will be be back
working on Thursday and Friday (at a hackathon). That should give me the
opportunity to have a look. If not, I will be back in the office on May 7.

Thanks for your patience,
Jc

**Comment by henryiii** [comment]
Hi Jc,

Thanks, enjoy your vacation and the hackathon - those are usually fun.  Just wanted to make sure it was on your radar to check. :) Now that Pip 10 is released, scikit-build is significantly easier to provide as a dependency (at least once Pip 10 works through the issues and becomes common).

In the next few days I'll try to rebase on master and make sure everything okay. 

Cheers,
Henry

**Comment by jcfr** [comment]
> Any suggestions? it passes tests, the only x is due to codecov thinking that there are 0.07% fewer tested lines.

This PR should help: https://github.com/scikit-build/scikit-build/pull/316

**Comment by jcfr** [comment]
Fix for the generation of manifest using `git` will be integrated in a different PR

**Pull request merged**
