### PR TITLE
Add UsePythonExtensions

### PR DESCRIPTION
**Pull request by jcfr**
This PR supersedes https://github.com/scikit-build/scikit-build/pull/304 originally submitted by `@xoviat`

### CODE REVIEW

**Comment by benbovy** [comment]
@jcfr -- Are this PR and #413 ready to merge? 

I'm close to release the next version of ``fastscapelib-fortran`` and I was wondering whether or not I should wait a bit so that I could reuse your work (based on these changes) to provide conda packages on windows for that release.

**Comment by jcfr** [comment]
Hi Benoit,

These past few weeks have been hectic, I will plan on doing a release of scikit-build next week. Would that work ? 

Thanks again for your patience, 
J-Christophe

**Comment by benbovy** [comment]
Yes of course! Thank you for your work!

**Comment by jcfr** [comment]
#413  has just been rebased, as soon as CI completes it will be integrated.

That said, we don't have a text for generating python module from `*.pyf`, is it something you could help with at some point ? 

If you provide me with a small demo project, I could take care of adding to the test suite. For reference:
* sample projects used for testing: https://github.com/scikit-build/scikit-build/tree/master/tests/samples
* tests: https://github.com/scikit-build/scikit-build/tree/master/tests

What thinking we could add a sample projects called `hello-fortran-pyf` and `hello-fortran-f90`  ?

**Comment by jcfr** [comment]
Closing. Corresponding changes integrated in https://github.com/scikit-build/scikit-build/commit/afa978814325336ac318316ded64e3a82cf3bcf7

**Pull request closed without merging**
